title: Speak For Me
email: info@speakforme.in
description: >
  Speak for Me
baseurl: ""
url: "https://speakforme.in"
twitter_username: speakforme
github_username:  speakforme
# Build settings
markdown: kramdown
google_analytics: UA-82421266-2
